// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/soc_dem_group/soc_dem_group.proto

package soc_dem_group

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SocDemGroup struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocDemGroup) Reset()         { *m = SocDemGroup{} }
func (m *SocDemGroup) String() string { return proto.CompactTextString(m) }
func (*SocDemGroup) ProtoMessage()    {}
func (*SocDemGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_059e0214cbcf9e7a, []int{0}
}

func (m *SocDemGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocDemGroup.Unmarshal(m, b)
}
func (m *SocDemGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocDemGroup.Marshal(b, m, deterministic)
}
func (m *SocDemGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocDemGroup.Merge(m, src)
}
func (m *SocDemGroup) XXX_Size() int {
	return xxx_messageInfo_SocDemGroup.Size(m)
}
func (m *SocDemGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_SocDemGroup.DiscardUnknown(m)
}

var xxx_messageInfo_SocDemGroup proto.InternalMessageInfo

func (m *SocDemGroup) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SocDemGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*SocDemGroup)(nil), "soc_dem_group.SocDemGroup")
}

func init() {
	proto.RegisterFile("proto/soc_dem_group/soc_dem_group.proto", fileDescriptor_059e0214cbcf9e7a)
}

var fileDescriptor_059e0214cbcf9e7a = []byte{
	// 105 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0xce, 0x4f, 0x8e, 0x4f, 0x49, 0xcd, 0x8d, 0x4f, 0x2f, 0xca, 0x2f, 0x2d, 0x40,
	0xe5, 0xe9, 0x81, 0x55, 0x08, 0xf1, 0xa2, 0x08, 0x2a, 0x19, 0x72, 0x71, 0x07, 0xe7, 0x27, 0xbb,
	0xa4, 0xe6, 0xba, 0x83, 0xb8, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0xcc, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x41, 0x60, 0x76, 0x12, 0x1b, 0xd8, 0x20, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xd4, 0x1f, 0xf9, 0xa6, 0x73, 0x00, 0x00, 0x00,
}
