version: '3.7'

x-app_environment: &app_environment
  environment:
    - API_GRPC_PORT
    - API_GRPC_HOST
    - API_REST_PORT
    - API_REST_HOST
    - DB_DSN

services:
  rotation_banner:
    build:
      context: ./rotation_banner
    restart: unless-stopped
    volumes:
      - ./rotation_banner:/app:cached
    ports:
      - "8000:8000"
    <<: *app_environment

  db:
    image: postgres:12-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 15145:5432