version: '3.7'

x-app_environment: &app_environment
  environment:
    - API_GRPC_PORT
    - API_GRPC_HOST
    - API_REST_PORT
    - API_REST_HOST
    - METRICS_PORT
    - METRICS_HOST
    - DB_DSN
    - AMQP_DSN
    - QUEUE_NAME

services:
  rotation_banner:
    build:
      context: ./rotation_banner
    restart: unless-stopped
    command: wait-for db:5432 -t 10 -- make run
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./rotation_banner:/app:cached
    ports:
      - "8000:8000"
    <<: *app_environment

  db:
    image: postgres:12-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 15145:5432

  integrations_test:
    build:
      context: ./integrations_test
    volumes:
      - ./integrations_test:/opt/integration_tests:delegated
    depends_on:
      - db
      - rabbitmq
    links:
      - db
      - rotation_banner
    command: go test
    <<: *app_environment