// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/banner/banner.proto

package banner

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	slot "proto/slot"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Banner struct {
	Id                   int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Slot                 *slot.Slot `protobuf:"bytes,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Description          string     `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Banner) Reset()         { *m = Banner{} }
func (m *Banner) String() string { return proto.CompactTextString(m) }
func (*Banner) ProtoMessage()    {}
func (*Banner) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6d60cbe54adb6f7, []int{0}
}

func (m *Banner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Banner.Unmarshal(m, b)
}
func (m *Banner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Banner.Marshal(b, m, deterministic)
}
func (m *Banner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Banner.Merge(m, src)
}
func (m *Banner) XXX_Size() int {
	return xxx_messageInfo_Banner.Size(m)
}
func (m *Banner) XXX_DiscardUnknown() {
	xxx_messageInfo_Banner.DiscardUnknown(m)
}

var xxx_messageInfo_Banner proto.InternalMessageInfo

func (m *Banner) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Banner) GetSlot() *slot.Slot {
	if m != nil {
		return m.Slot
	}
	return nil
}

func (m *Banner) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Banner)(nil), "banner.Banner")
}

func init() { proto.RegisterFile("proto/banner/banner.proto", fileDescriptor_c6d60cbe54adb6f7) }

var fileDescriptor_c6d60cbe54adb6f7 = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4a, 0xcc, 0xcb, 0x4b, 0x2d, 0x82, 0x52, 0x7a, 0x60, 0x31, 0x21, 0x36, 0x08,
	0x4f, 0x4a, 0x14, 0xa2, 0xa4, 0x38, 0x27, 0xbf, 0x04, 0x4c, 0x40, 0xa4, 0x95, 0xa2, 0xb8, 0xd8,
	0x9c, 0xc0, 0x0a, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83,
	0x98, 0x32, 0x53, 0x84, 0xe4, 0xb8, 0x58, 0x40, 0xea, 0x24, 0x98, 0x14, 0x18, 0x35, 0xb8, 0x8d,
	0xb8, 0xf4, 0xc0, 0x9a, 0x82, 0x73, 0xf2, 0x4b, 0x82, 0xc0, 0xe2, 0x42, 0x0a, 0x5c, 0xdc, 0x2e,
	0xa9, 0xc5, 0xc9, 0x45, 0x99, 0x05, 0x25, 0x99, 0xf9, 0x79, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0xc8, 0x42, 0x49, 0x6c, 0x60, 0x2b, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x74,
	0x87, 0x7f, 0x9e, 0x00, 0x00, 0x00,
}
